IMAGE_SIZE:
  - 448
  - 448

S: 7
B: 2
C: 20

VOC_DETECTION_CATEGORIES:
  - "__background__"
  - "aeroplane"
  - "bicycle"
  - "bird"
  - "boat"
  - "bottle"
  - "bus"
  - "car"
  - "cat"
  - "chair"
  - "cow"
  - "diningtable"
  - "dog"
  - "horse"
  - "motorbike"
  - "person"
  - "pottedplant"
  - "sheep"
  - "sofa"
  - "train"
  - "tvmonitor"

L_coord: 5.0
L_obj: 1.0
L_noobj: 0.5
L_class: 1.0

Rescore: False
Sqrt: True

BATCH_SIZE: 64
NUM_EPOCHS: 155

Jitter: 0.1
Brightness: 1.5
Saturation: 1.5
Hue: 0.1

BACKBONE_LR: 0.00001
HEAD_LR: 0.001
PCT_START: 0.3
WEIGHT_DECAY: 0.0005
